<?php

/**
 * Implementation of hook_perm().
 */
function hpos_services_perm() {
    return array('key validation');
}

/**
 * Implementation of hook_service().
 */
function hpos_services_service() {

    return array(
        // reseller  functions
        // add
        array(
            '#method' => 'hpos.key_setup',
            '#callback' => 'hpos_services_get_key_status',
            '#file' => array('file' => 'inc', 'module' => 'hpos_services'),
            '#access callback' => 'hpos_services_access',
            '#access arguments' => array('key validation'),
            '#args' => array(
                array(
                    '#name' => 'key',
                    '#type' => 'string',
                    '#description' => t('Name if reseller'),
                ),
                array(
                    '#name' => 'owner',
                    '#type' => 'string',
                    '#description' => t('Comment if reseller'),
                ),
                 array(
                    '#name' => 'email',
                    '#type' => 'string',
                    '#description' => t('Comment if reseller'),
                ),
                 array(
                    '#name' => 'mobile',
                    '#type' => 'string',
                    '#description' => t('Comment if reseller'),
                )
            ),
            '#return' => 'struct',
            '#help' => 'Provide all required arguments'
        ),
    );
}



function hpos_services_access() {
    return TRUE;
}