<?php

define('ACTIVE', 1);
define('BLOCKED', 0);

/**
 * Implementation of hook_perm().
 */
function hpos_services_perm() {
  return array('key validation');
}

/**
 * Implementation of hook_service().
 */
function hpos_services_service() {

  return array(
    array(
      '#method' => 'hpos.key_setup',
      '#callback' => 'hpos_services_get_key_status',
      '#file' => array('file' => 'inc', 'module' => 'hpos_services'),
      '#access callback' => 'hpos_services_access',
      '#access arguments' => array('key validation'),
      '#args' => array(
        array(
          '#name' => 'key',
          '#type' => 'string',
          '#description' => t('License key'),
        ),
        array(
          '#name' => 'owner',
          '#type' => 'string',
          '#description' => t('Comment if reseller'),
        ),
        array(
          '#name' => 'email',
          '#type' => 'string',
          '#description' => t('Comment if reseller'),
        ),
        array(
          '#name' => 'mobile',
          '#type' => 'string',
          '#description' => t('Comment if reseller'),
        )
      ),
      '#return' => 'struct',
      '#help' => 'Provide all required arguments'
    ),
  );
}

function hpos_services_access() {
  return TRUE;
}

/**
 * Implementation of hook_user().
 */
function hpos_services_user($type, &$edit, &$user, $category = NULL) {
  switch ($type) {
    case 'load':
      // Only add links if we are on the user 'view' page.
      if (arg(0) != 'user' || arg(2)) {
        return;
      }
      return profile_load_profile($user);
    case 'register':
      return profile_form_profile($edit, $user, $category, TRUE);
    case 'update':
      return profile_save_profile($edit, $user, $category);
    case 'insert':
      return profile_save_profile($edit, $user, $category, TRUE);
    case 'view':
      $license_key = db_fetch_object(db_query('SELECT license_key FROM {hpos_keys} WHERE uid = %d', $user->uid));
      $user->content['summary']['license_key'] = array(
        '#type' => 'user_profile_item',
        '#title' => t('HEIDI POS License Key'),
        // l() escapes the attributes, so we should not escape !username here.
        '#value' => '',
        '#attributes' => array('class' => 'license_key'),
      );
    case 'form':
      return profile_form_profile($edit, $user, $category);
    case 'validate':
      return profile_validate_profile($edit, $category);
    case 'delete':
      db_query('DELETE FROM {hpos_keys} WHERE uid = %d', $user->uid);
  }
}